#@data/values
---
git_uri: git@github.com:blinkbitcoin/price.git
git_branch: main
git_charts_uri: git@github.com:blinkbitcoin/charts.git
git_charts_branch: main
git_charts_bot_branch: bot-bump-price-image
github_private_key: ((github-blinkbitcoin.private_key))
github_app_id: ((github-blinkbitcoin.github_app_id))
github_app_private_key: ((github-blinkbitcoin.github_app_private_key))
docker_registry: us.gcr.io/galoy-org
docker_registry_user: ((docker-creds.username))
docker_registry_password: ((docker-creds.password))
docker_host_ip: ((staging-ssh.docker_host_ip))
